const translations={es:{
'nav.about':'Sobre JPFR','nav.projects':'Proyectos','nav.ethics':'Ética de IA','nav.vision':'Visión','nav.contact':'Contacto','nav.collaborate':'Colaborar',
'hero.eyebrow':'Psiquiatría · Tecnología humanitaria · Comunidad','hero.line1':'Construyendo tecnología','hero.line2':'para la dignidad humana.','hero.lede':'Soy Juan Pablo Fernández Rebosio — psiquiatra, creador y Community Builder. Desarrollo sistemas éticos que conectan salud mental, documentación audiovisual responsable, IA accesible y colaboración internacional.','hero.explore':'Explorar el ecosistema','hero.contact':'Iniciar una conversación','hero.principles':'Privacidad desde el diseño','hero.human':'Revisión humana','hero.community':'Orientación comunitaria','hero.card1':'Documentar','hero.card2':'Proteger','hero.card3':'Conectar',
'about.label':'Sobre JPFR','about.title':'Una práctica multidisciplinaria en la intersección del cuidado, la creatividad y la tecnología.','about.p1':'JPFR es la identidad autoral y profesional de Juan Pablo Fernández Rebosio, psiquiatra argentino–italiano y fundador de Landia’s Productions.','about.p2':'Su trabajo explora cómo la tecnología ética, el conocimiento en salud mental y la cultura audiovisual pueden ayudar a las comunidades a documentar responsablemente, comunicarse con seguridad, recuperarse del trauma y colaborar entre países.','about.tag1':'Psiquiatría','about.tag2':'Enfoque informado por trauma','about.tag3':'Innovación humanitaria','about.tag4':'Dirección creativa','about.tag5':'Derechos digitales',
'projects.label':'El ecosistema','projects.title':'Una visión. Múltiples iniciativas conectadas.','projects.intro':'Landia’s Productions es el marco creativo y estratégico que conecta narrativas, documentación responsable, salud pública e innovación ética.','projects.saving':'Una iniciativa humanitaria y de salud pública que conecta salud mental, resiliencia comunitaria, educación para emergencias y tecnología responsable.','projects.undercover':'Un concepto centrado en la privacidad para preservar, organizar y gestionar de forma controlada y con revisión humana información sensible.','projects.evidence':'Flujos de trabajo para metadatos, hashes, indexación, procedencia y preparación responsable de cadena de custodia.','projects.reporter':'Un sistema personal y documental para narrativas estructuradas, cronologías, notas multilingües y registros autorizados.','projects.streaming':'Comunicación en vivo y producción audiovisual responsable, separando claramente contenido público y evidencia confidencial.','projects.world':'Un universo creativo original de personajes, libros, música, performance, cultura visual y narración multimedia.',
'ethics.label':'Ética de IA & Community Builder','ethics.title':'La IA debe asistir a las personas, nunca reducir sus derechos.','ethics.copy':'La capa aprobada AI Ethics & Community Builder guía cada futuro componente de la consola. Prioriza dignidad, consentimiento informado, supervisión humana, privacidad, accesibilidad y uso responsable.','ethics.p1':'Revisión humana por defecto','ethics.p2':'Privacidad y minimización de datos','ethics.p3':'Sin vigilancia no autorizada','ethics.p4':'Procedencia y auditabilidad','ethics.p5':'Accesibilidad e inclusión','ethics.p6':'Beneficio comunitario',
'vision.label':'Visión a largo plazo','vision.quote':'“La tecnología debe fortalecer comunidades, apoyar el cuidado y proteger la dignidad humana, sin reemplazar el juicio ni comprometer derechos.”','vision.copy':'JPFR está construyendo un marco de colaboración ética entre profesionales de la salud, investigadores, desarrolladores, documentalistas, educadores, organizaciones humanitarias y participantes de la comunidad.','roadmap.now.title':'Fundamentos','roadmap.now.copy':'Portfolio, gobernanza, marco ético y prueba de concepto.','roadmap.next.title':'Pilotos con socios','roadmap.next.copy':'Colaboraciones pequeñas, legales y con revisión humana.','roadmap.future.title':'Infraestructura comunitaria','roadmap.future.copy':'Sistemas resilientes, accesibles y de colaboración internacional.',
'contact.label':'Colaborar','contact.title':'Construyamos algo al servicio de las personas.','contact.copy':'Abierto a colaboraciones éticas con organizaciones humanitarias, instituciones de investigación, equipos de derechos digitales, profesionales de la salud, tecnólogos responsables y socios creativos.','contact.note':'Contacto escrito preferido · Buenos Aires, Argentina · Colaboración internacional','footer.copy':'Psiquiatría, creatividad y tecnología ética para la dignidad humana y la comunidad.'}}
document.querySelectorAll('[data-i18n]').forEach(el=>{el.dataset.en=el.textContent});
let lang='en';
const btn=document.getElementById('languageToggle');
btn.addEventListener('click',()=>{
  lang=lang==='en'?'es':'en';
  document.documentElement.lang=lang;
  btn.textContent=lang==='en'?'ES':'EN';
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const key=el.dataset.i18n;
    el.textContent=lang==='es'&&translations.es[key]?translations.es[key]:el.dataset.en;
  });
});
const toggle=document.getElementById('menuToggle'),panel=document.getElementById('mobilePanel');toggle.addEventListener('click',()=>{const open=panel.classList.toggle('open');toggle.setAttribute('aria-expanded',open);panel.setAttribute('aria-hidden',!open)});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.getElementById('year').textContent=new Date().getFullYear();
